name: OR4ESA-env
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel=6.29
  - pip=25.0
  - python=3.12
  - pip:
      - gurobipy==12.0.1
      - highspy==1.9.0
      - linopy==0.5.0
      - plotly==6.0.1
      - pyyaml==6.0.2
      - xarray==2025.1.2
      - numpy==1.26.4
      - pandas==2.2.3
      - polars-lts-cpu
      - matplotlib==3.10.1
      - nbformat==5.10.4
      - requests==2.32.3 

      
